### ISSUE TITLE
Crash Upon Loading

### ISSUE THREAD

**Issue by vizthex123** [ReinaSHSL/Yohane-#1]
I've got Friendly Minions installed as well, but it gives me this error whenever I try to load the game with these  mods enabled: [![Screenshot from Gyazo](https://gyazo.com/bcba70f9cfddd00d0cf8b8d0d9a56634/raw)](https://gyazo.com/bcba70f9cfddd00d0cf8b8d0d9a56634)

**Comment by ReinaSHSL** [comment]
Are you running an old version of Colored Maps? If so, update and it should fix.
