### ISSUE TITLE
Excitement removes all fallen energy

### ISSUE THREAD

**Issue by mPelland42** [ReinaSHSL/Yohane-#11]
## Expected Behavior
Play excitement - deal damage equal to half your fallen energy.  Pay 4 fallen energy

## Actual Behavior
Deals damage equal to half my fallen energy, removes _all_ of my fallen energy, then removes 4 more leaving me with -4 fallen energy.
## Steps to Reproduce the Problem

  1. play excitement.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ReinaSHSL** [comment]
fixed
