### ISSUE TITLE
v1.0.8

### ISSUE THREAD

**Issue by Celicath** [ReinaSHSL/Yohane-#16]
The bug reporting guy strikes back. Please don't delete the mod.

- Ruby's attack is STILL affected by enemies' power. Parameters on applyPowers in RubyAttack seems to be reversed.
- Go All Out now draws before Exhausting cards, and it doesn't exhaust non-attack cards from the newly drawn cards. If the deck is shuffled, many cards from the deck are not Exhausted. Something something AddToTop
- wHY mOdOrE a sKiLL?
- Allure of Darkness+ is unusable when you have no fallen energy buff icon... again.

**Comment by ReinaSHSL** [comment]
fixed all bug modore.

fuck splicing images again ez
