### ISSUE TITLE
base mod update revision

### ISSUE THREAD

**Issue by 5m1l35** [ReinaSHSL/Yohane-#2]
Unfortunately with the new version of slay the spire required a new version of mod the spire which means that your mod no longer works. I would greatly appreciate it if you would put the work into fix this tho I understand that it requires I would guess alot of work from you which you may not want to put in which is understandable.

**Comment by ReinaSHSL** [comment]
My life is rather turbulent right now, once everything calms down and I have more time to sit down and code I'll update!

**Comment by 5m1l35** [comment]
Totally understand hope things clear up for you. Thanks for the response
wish you the best.
