### ISSUE TITLE
Excitement & Hell Zone always deal 0 damage

### ISSUE THREAD

**Issue by yhrcyt** [ReinaSHSL/Yohane-#3]
## Expected Behavior
When I started the turn with 5 fallen energy, Excitement/Hell Zone should deal damage.

## Actual Behavior
When I have 5 fallen energy and play Excitement/Hell Zone, it deal 0 damage instead. And no matter how much fallen energy I have, it always deal 0 damage.

## Steps to Reproduce the Problem

  1.Start a new game using The Fallen Angel and enter a battle.
  2.Press ` to open debug menu, input "hand add Yohane:Excitement" or "hand add Yohane:Hell_Zone", then play it.
  3.See? It always deal 0 damage.

## Specifications

  - Version: Yohane: 1.0.0.0; BaseMod: 3.3.0; ModTheSpire: 3.2.0; FriendlyMinions: 0.1
  - Platform:
  - Subsystem:

**Comment by ReinaSHSL** [comment]
Fixed
